MugedaHelper={};function G(a){return document.getElementById(a)}function E(a,c,b){c||(c="load");b||(b=window);b.attachEvent?b.attachEvent("on"+c,a):b.addEventListener(c,a,false)}function json(a){try{return eval("("+a+")")}catch(c){return null}}function _106(a){if(!a||typeof a=="string")return a;var c="",b;for(b in a)c+="&"+b+"="+encodeURIComponent(a[b]);c&&(c=c.substr(1));return c}
function ajax(a){var c=/POST/i.test(a.type),b=a.data||"",e=a.dataType,f=a.url||location.href,d=/\?/.test(f)?"&":"?",g=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Msxml2.XMLHTTP")||new ActiveXObject("Microsoft.XMLHTTP");g.onreadystatechange=function(b){if(g.readyState==4)g.status==200?(b=g.responseText,e=="json"&&(b=json(b)),(c=a.success)&&c(b)):a.error&&a.error(g.status,g)};if(typeof b=="object"){var k=[],h;for(h in b)k.push(encodeURIComponent(h)+"="+encodeURIComponent(b[h]));b=k.join("&")}g.open(c?
"POST":"GET",f+(c?"":(b?d:"")+b+(a.cache?"":(!b&&d=="?"?"?":"&")+(a.cache_ok?"":"_="+(new Date).getTime()))),a.async===false?false:true);c&&g.setRequestHeader("Content-Type","application/x-www-form-urlencoded");g.send(b);return g}
var ajaxHelper=function(a){a=a||{};a.method=a.method||"GET";a.type=(a.type||"text").toLowerCase();a.jsonp_callback=a.jsonp_callback||"callback";a.success=a.success||function(){};a.error=a.error||function(){};a.cache_ok=a.cache_ok||false;a.url=a.url||(a.error({status:-5,desc:"Empty url"}),"");var c=(new Date).getTime()+Math.random();window.hashOptions=window.hashOptions||{};window.hashOptions[c]=a;window.hashOptions[""]=a;a.cache_ok||(a.url+=a.url.indexOf("?")>-1?"&":"?",a.url+="_mats="+c,a.url+="&callback="+
a.jsonp_callback);if(a.type=="jsonp"){window[a.jsonp_callback]=function(c){window.hashOptions[c._mats||""].success(c);delete window[a.jsonp_callback]};var b=document.getElementsByTagName("head")[0],e=document.createElement("script");e.type="text/javascript";e.src=a.url;e._mats=c;e.onload=function(){};e.onerror=function(){window.hashOptions[this._mats||""].error({status:-2,desc:"Failed to load the url: "+a.url})};b.appendChild(e)}else if(a.type=="fetch"&&window.fetch)try{fetch(a.url,{method:a.method||
"GET",credentials:a.credentials||"include"}).then(function(c){c.status!==200?a.error&&a.error({status:c.status,desc:"Error in fetching data "+c.statusText}):c.json().then(function(c){a.success(c)})})}catch(f){a.error&&a.error({status:-1,desc:"Error in fetching data "+f.toString()})}else{var d;window.XMLHttpRequest?d=new XMLHttpRequest:a.error({status:-3,desc:"Platform not supported"});d.withCredentials=a.withCredentials||true;d.onreadystatechange=function(){if(d.readyState==4)if(d.status==200){var c=
"ok";if(a.type=="json")try{a.success(JSON.parse(d.responseText))}catch(b){c=b.toString(),a.error({status:-6,desc:"Error in parsing JSON ("+c+")"})}else a.type=="data"||a.type=="buffer"?a.success(d.response):a.type=="text"&&a.success(d.responseText)}else a.error({status:d.status,desc:"Error in fetching data (code "+d.status+")"})};if(a.type=="data")d.responseType="blob";else if(a.type=="buffer")d.responseType="arraybuffer";d.open(a.method,a.url,true);d.send()}};
function isMobile(){return navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/i)||navigator.userAgent.match(/Windows Phone/i)?true:false}function fo(a){var c=0,b=0;do c+=a.offsetLeft||0,b+=a.offsetTop||0;while(a=a.offsetParent);return{x:c,y:b}}function fe(a){a=a||event;return{x:a.pageX||a.x,y:a.pageY||a.y}}
function fc(a){a&&a.stopPropagation?a.stopPropagation():event.cancelBubble=true}function getClass(a,c){for(var b=RegExp("(^|\\s*)"+a+"(\\s*|$)"),e=c?document.getElementsByTagName(c):document.getElementsByTagName("*")||document.all,f=[],d=0,g=e.length;d<g;d++)b.test(e[d].className)&&f.push(e[d]);return f}JSON.clone=function(a){return JSON.parse(JSON.stringify(a))};
function getElementOffset(a){for(var c=0,b=0;a&&a.tagName!="BODY";)c+=a.offsetTop,b+=a.offsetLeft,a=a.offsetParent;return{top:c,left:b}}Mugeda=window.Mugeda||{};var MugedaTools=window.MugedaTools=window.MugedaTools||{};
MugedaTools.message=function(){var a,c=[],b={},e=function(){var a=window.getComputedStyle(document.documentElement,""),a=(Array.prototype.slice.call(a).join("").match(/-(moz|webkit|ms)-/)||["",""])[1];return{dom:"WebKit|Moz|MS".match(RegExp("("+a+")","i"))[1],lowercase:a,css:"-"+a+"-",js:a[0].toUpperCase()+a.substr(1)}}();return{show:function(f,d){d=d||{};if(!a){var g=document.createElement("div");g.className="mugeda_mask";var k=d.parent||document.body,h=d.hideShade,i=d.center,t=d.clickable,r=g.appendChild(document.createElement("div")),
j=r.appendChild(document.createElement("div")),m=r.appendChild(document.createElement("div"));g.style.cssText=t?"text-align: center; display: block; position: absolute;left: 50%; top: 50%; transform: translate(-50%, -50%);":"position:fixed;left:0;right:0;top:0;bottom:0;text-align:center;line-height:"+(d.parent?k.offsetHeight:document.body.clientHeight||document.documentElement.clientHeight)+"px";r.style.cssText="padding-top:10px; line-height:30px;display:inline-block;padding:8px; background-color:rgba(0,0,0,"+
(h?0:0.6)+");border-radius:4px;"+(i?"position:relative;top:32px;":"");r.align="center";j.style.cssText="width: 24px; height: 24px; display: block; border-radius: 50%; border-left: 2px solid #F36523; border-top: 2px solid #F36523; border-right: 2px solid white; border-bottom: 2px solid white; margin: 16px;";m.style.cssText='text-align:center;color:#fff;font:normal 12px "microsoft yahei";';m.innerHTML=f||"";a=k.appendChild(g);h="from {"+e.css+"transform:rotate( 0deg ) }to {"+e.css+"transform:rotate( 360deg ) }";
g=document.createElement("style");document.head.appendChild(g);g=g.sheet;k="spin_"+(new Date).getTime();h="@"+e.css+"keyframes "+k+"{ "+h+"}";if(c.length)i=c.pop().name,t=b[i],delete b[i],g.deleteRule(t),g.insertRule(h,t),b[k]=t;else{i=g.cssRules.length;try{g.insertRule(h,i)}catch(p){}b[k]=i}j.style.cssText+=e.css+"animation:"+k+" 1200ms linear infinite;"}},close:function(){a&&(a.parentNode.removeChild(a),a=null)}}}();
MugedaTools.iterate=function(a,c,b){for(var e in a)a.hasOwnProperty(e)&&(typeof a[e]=="object"?iterate(a[e],c+"."+e,b):b&&b(a,e))};
MugedaTools.detectSecurityRisk=function(a){a=(a||"").toLowerCase();return a.match(/\b(fscommand|onabort|onactivate|onafterprint|onafterupdate|onbeforeactivate|onbeforecopy|onbeforecut|onbeforedeactivate|onbeforeeditfocus|onbeforepaste|onbeforeprint|onbeforeunload|onbeforeupdate|onblur|onbounce|oncellchange|onchange|onclick|oncontextmenu|oncontrolselect|oncopy|oncut|ondataavailable|ondatasetchanged|ondatasetcomplete|ondblclick|ondeactivate|ondrag|ondragend|ondragleave|ondragenter|ondragover|ondragdrop|ondragstart|ondrop|onend|onerror|onerrorupdate|onfilterchange|onfinish|onfocus|onfocusin|onfocusout|onhashchange|onhelp|oninput|onkeydown|onkeypress|onkeyup|onlayoutcomplete|onload|onlosecapture|onmediacomplete|onmediaerror|onmessage|onmousedown|onmouseenter|onmouseleave|onmousemove|onmouseout|onmouseover|onmouseup|onmousewheel|onmove|onmoveend|onmovestart|onoffline|ononline|onoutofsync|onpaste|onpause|onpopstate|onprogress|onpropertychange|onreadystatechange|onredo|onrepeat|onreset|onresize|onresizeend|onresizestart|onresume|onreverse|onrowsenter|onrowexit|onrowdelete|onrowinserted|onscroll|onseek|onselect|onselectionchange|onselectstart|onstart|onstop|onstorage|onsyncrestored|onsubmit|ontimeerror|ontrackchange|onundo|onunload|onurlflip|seeksegmenttime|javascript|eval|fromcharcode|window(\.|\['|\[")|document(\.|\['|\["))\b/g)||a.match(/\b(background\-image\s*\:|background\s*\:|href\s*\=|src\s*\=|style\s*\=)/g)||
a.match(/\<(script|link|img|input|style|meta|iframe|frame|table|td|tr|div|base|object|embed|xml)/g)};
MugedaMraid={mraidReadyStatus:0,mraidState:void 0,getStage:function(){var a=null;for(window.event&&(a=window.event.target||window.event.srcElement);a;){if((a.id||"").indexOf("_stage")>0||a.getAttribute&&a.getAttribute("data-mid")==0)break;a=a.parentNode}return a?a:document.getElementsByClassName("MugedaStage")[0]},setMraidState:function(a){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var c=_mrmcp.display_mode,b=mraid.getPlacementType();this.mraidState=a.toLowerCase();var e=document.getElementById("mugeda_close_button");
switch(this.mraidState){case "default":if(c!="expand"&&b!="interstitial"&&e)e.style.display="none";typeof Mugeda!="undefined"&&Mugeda.gotoAndPlay&&Mugeda.gotoAndPlay(1);break;case "expanded":(c=="auto"||c=="expand"||c=="interstitial")&&setTimeout(function(){e.style.display="block"},50);break;case "resized":setTimeout(function(){e.style.display="block"},50)}},openLink:function(a,c){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;_mrmcp.destination_url&&_mrmcp.destination_url.indexOf("%DESTURL%")<0&&(a=
_mrmcp.destination_url);if(a){var b=a,e="ts="+(new Date).getTime();e+="&_moid="+(_mrmcp.owner_id||"");e+="&_mcid="+(_mrmcp.creative_id||"");e+="&_mw="+(_mrmcp.width||"");e+="&_mh="+(_mrmcp.height||"");e+="&_mtp="+(_mrmcp.type||"");e+="&_mtt="+encodeURIComponent(_mrmcp.title||"");var f=_mrmcp.custom_params;f&&f.indexOf("%CUSTOMPARAM%")<0&&(e+="&"+f);if((f=_mrmcp.redirect_url)&&f.indexOf("%LINK%")<0)var d=a.indexOf("?"),b=d<0?"?":"&",b=a=f+(f.lastIndexOf("=")==f.length-1?encodeURIComponent(a+b+e):"");
var g=a.split("#"),f="";g.length>1&&(f=g[1],a=g[0]);var d=a.indexOf("?"),g=d<0?"?":"&",d=d==a.length-1,k=window.location.search;if(k){for(var k=k.split("?")[1],h=k.split("&"),i=h.length,t=0;t<i;t++){var r=h[t].split("=");if(r.length==2){var j=r[1];r[0].toLowerCase()=="mugeda_click_link"&&(a=unescape(j),d=a.indexOf("?"),g=a<0?"?":"&",d=d==a.length-1)}}a+=(d?"":g)+k;d=false;k.length&&(g="&")}a+=(d?"":g)+e+(f?"#"+f:"");this.mraidReadyStatus==1?c=="internal"?mraid.open(b):c=="expand"?this.expand(b,0):
window.open(b):c=="internal"?window.location=b:c=="expand"?this.expand(b):window.open(b);MugedaTracker.fireEvent({category:"link",action:c,label:a,value:0})}},expand:function(a,c,b){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;if(this.mraidReadyStatus!=1){if(a&&a.length){var e=document.URL.match(/client.*preview.*id/),f=b=null;try{b=(e?window:window.parent).document,f=b.getElementById("mugeda_expanded")||b.createElement("div")}catch(d){window.open(a);return}a.match(/^(\/|http:|https:)/i)||(a=(_mrmcp.creative_path||
"")+a);f.id="mugeda_expanded";f.style.display="block";f.style.position="fixed";f.style.width=(b.defaultView.innerWidth||b.documentElement.clientWidth)+"px";f.style.height=(b.defaultView.innerHeight||b.defaultView.innerHeight)+"px";f.style.left="0px";f.style.margin="0";f.style.padding="0";f.style.border="none";f.style.top="0px";f.style.background="#000";f.innerHTML="<iframe id='mugeda_expand_iframe' src='"+a+"' style='border:none;width:100%;height:100%;margin:0px;padding:0px;'></iframe>";b.body.appendChild(f);
MugedaBehavior.processCloseButton("expand",b)}}else{var b=b||{},f=mraid.getMaxSize(),e=parseInt(b.width)||f.width,f=parseInt(b.height)||f.height,a=a||b.url,g=!a||a.length==0;c==1?(a=parseInt(b.left)||0,b=parseInt(b.top)||0,MugedaBehavior.processCloseButton("resize"),mraid.setResizeProperties({width:e,height:f,offsetX:a,offsetY:b,allowOffscreen:false}),mraid.resize()):(mraid.setExpandProperties({width:e,height:f,isModal:true,useCustomClose:_mrmcp.display_mode?true:false}),g?(mraid.expand(),MugedaBehavior.processCloseButton()):
mraid.expand(a))}},sendEmail:function(a){window.open("mailto:"+a.email_addr+"?subject="+a.email_title+"&body="+a.email_body,"_self")},savePicture:function(a){this.mraidReadyStatus==1&&mraid.supports("storePicture")&&mraid.storePicture(a.url)},addCalendarEvent:function(a){this.mraidReadyStatus==1&&mraid.supports("calendar")&&mraid.createCalendarEvent({summary:a.calendar_summary,description:a.calendar_desc,location:a.calendar_location,start:a.calendar_start_time,end:a.calendar_end_time})},createHTML5VideoTag:function(a,
c){if(a){var b="_"+ +new Date,e=0,f=0;a.data&&(b="_"+a.data.guid,a.data.param&&(e=a.data.param.continueAudio||0,f=a.data.param.clickStatus||0));var d=G("mugeda_video"+b);if(d)return d.parentNode;div=document.createElement("div");div.className="mugedaVideoHolder";div.style.margin=0;div.style.padding=0;div.style.backgroundColor="rgba(0,0,0,0)";div.style.position="absolute";div.style.top=0;div.style.left=0;div.style.width=0;div.style.height=0;div.style.zIndex=1;div.style.display="none";_mrmcp=typeof _mrmcp==
"undefined"?{}:_mrmcp;var g=(_mrmcp.creative_path||"")+"close_button.png",k=navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i);div.innerHTML='<video id="mugeda_video'+b+'" '+(c.video_embed?'x5-video-player-type="h5" x5-video-player-fullscreen="true"':"")+' controls playsinline x-webkit-airplay webkit-playsinline x5-playsinline preload="auto" video-id="'+c.id+'"  video-mode="'+c.mode+'" video-name="'+c.name+'"  style="width:100%;height:100%;position:absolute;z-index:2;}"></video>'+
('<div id="mugeda_video_close'+b+'" align="middle" style="position: absolute;color:white;width:36px;height:36px;right:0px;top: '+(k?0:0)+"px;cursor:pointer;background-image:url("+g+');z-index:3;"></div>');a.appendChild?a.appendChild(div):a.dom&&a.dom.appendChild(div);d=G("mugeda_video"+b);b=G("mugeda_video_close"+b);b.style.display=c.close_button?"block":"none";c.close_button&&(g=isMobile()?"touchend":"click",b.addEventListener(g,function(a){a.stopPropagation();d.src="";d.rawSrc="";d.load();div.style.display=
"none"},false));c.video_controls?d.setAttribute("controls","controls"):d.removeAttribute("controls");d.rawPlay=d.play;d.rawPause=d.pause;d.play=function(){if(d.paused){if((d.src==""||d.src==window.location.href)&&d.backSrc)d.src=d.backSrc;if(d.rawSrc==""&&d.backRawSrc)d.rawSrc=d.backRawSrc;d.onplayed();d.rawPlay();for(var a=d.parentElement;a;)if(a.className=="mugedaVideoHolder"){a.style.display="block";break}else a=a.parentElement}};d.pause=function(){d.onpaused();d.rawPause()};d.onplayed=function(){if(e==
0&&window.backgroundMusic)backgroundMusic.prevPlayStatus=backgroundMusic.playStatus,backgroundMusic.pause(),backgroundMusic.playStatus=0};d.onpaused=function(){if(e==0&&window.backgroundMusic&&backgroundMusic.prevPlayStatus==1)backgroundMusic.play(),backgroundMusic.playStatus=1,delete backgroundMusic.prevPlayStatus};d.onclick=function(a){a.preventDefault();a.stopPropagation();f===0?this.paused?this.play():this.pause():this.paused&&this.play()};return div}},loadUrl:function(a){var c=a.id||(new Date).getTime(),
b=a.url||"",e=a.left||0,f=a.top||0,d=isNaN(a.width)?window.aniData?window.aniData.width:320:Math.max(0,a.width),g=isNaN(a.height)?window.aniData?window.aniData.height:240:Math.max(0,a.height),k=a.before||null,h=a.style,i=a.scroll,t=a.parent,r=a.onload,j=a.onclose,m=a.position,p=a.close_position;if(!k&&!t){var q=typeof Mugeda!="undefined"&&Mugeda.getCanvas?Mugeda.getCanvas():this.getStage();typeof Mugeda!="undefined"&&q&&(q=getElementOffset(q),e+=q.left,f+=q.top)}var l=G(c);l||(l=document.createElement("div"),
t?t.appendChild(l):k?k.parentNode.insertBefore(l,k):document.body.appendChild(l));l.id=c;l.style.margin=0;l.style.padding=0;l.style.backgroundColor="transparent";l.style.position=m?m:"fixed";l.style.top=0;l.style.left=0;l.style.width=0;l.style.height=0;switch(p){case "leftTop":p="left:4px;top:4px;";break;case "leftbottom":p="left:4px;bottom:4px;";break;case "rightbottom":p="right:4px;bottom:4px;";break;default:p="right: 4px;top: 4px;"}l.innerHTML="<iframe "+(i?"":"scrolling=no ")+'id="'+c+'_iframe" style="border:none; width:100%;height:100%; '+
(i?"":"overflow:hidden;")+' " ></iframe>'+('<div id="'+c+'_iframe_close" align="middle" style="position: absolute;color:white;width: 24px;height: 24px; '+p+'cursor:pointer;background: rgba(0,0,0,0.5);border: 3px solid white;border-radius: 15px;font-family:arial;font-size: 16px;line-height:24px;">&#10006;</div>');l.style.display="none";l.style.top=f+"px";l.style.left=e+"px";l.style.width=d+"px";l.style.height=g+"px";l.style.display="block";l.style.cssText+=h;G(c+"_iframe_close").style.display=a.close_button?
"block":"none";setTimeout(function(){if(a.close_button)G(c+"_iframe_close").onclick=function(){l.style.display="none";G(c+"_iframe").src="about:blank";j&&j(l)}},100);setTimeout(function(){var a=G(c+"_iframe");a.src=b;if(r)try{a.onload=function(){r(a);a.onload=null}}catch(d){}},100);return l},playAudio:function(a,c){var b=false;if(!a||!a.audio_url||!a.audio_url.length)return false;var e=typeof Mugeda!="undefined"&&Mugeda.getAudioCache?Mugeda.getAudioCache(a.audio_url,a.audioId):MugedaBehavior.localCache[a.audio_url];
if(e){if(e.loop=parseInt(a.audio_loop)==1?true:false,e.play)if(e.webAudio)b=e.play(a.event=="click"||c?true:false);else if(a.event=="click"){try{e.pause(),e.currentTime=0}catch(f){}setTimeout(function(){e.play()},5)}else(e.playStatus!=1||c)&&setTimeout(function(){e.play();e.playStatus=1;b=true},10)}else{var e=new Audio,d=document.createElement("source"),g=a.audio_url.lastIndexOf("."),g=a.audio_url.substring(g+1),k=true;switch(g){case "ogg":d.type="audio/ogg";break;case "mp3":d.type="audio/mpeg";break;
default:k=false,console.log("Audio extension ("+g+") not supported.")}if(k){d.src=a.audio_url;e.appendChild(d);e.autoplay=false;e.preload="auto";e.load();var h=document.getElementById("mugeda_resource_loading");if(!h)h=document.createElement("img"),h.id="mugeda_resource_loading",h.style.position="fixed",h.style.right="2px",h.style.top="2px",h.style.display="block",h.src=(_mrmcp.creative_path||"")+"loading.gif",document.body.appendChild(h);h.style.display="block";b=true;e.addEventListener("canplay",
function(){h.style.display="none";e.play()},false);MugedaBehavior.localCache[a.audio_url]=e}}return b},playHTML5Video:function(a){var c=a.left||0,b=a.top||0,e=isNaN(a.width)?"100%":Math.max(0,a.width)+"px",f=isNaN(a.height)?"100%":Math.max(0,a.height)+"px",d=window.Mugeda&&Mugeda.getCanvas?Mugeda.getCanvas():this.getStage();typeof Mugeda!="undefined"&&d&&!a.video_holder&&!isNaN(a.left)&&(d=getElementOffset(d),c+=d.left,b+=d.top);var g=document.body;if(a.video_holder)if((d=Mugeda.getMugedaObject?Mugeda.getMugedaObject():
null)&&d.scene){var g=a.video_holder,g=g.split("/"),k=a.video_object===1;if(g.length===2)d=d.scene.getObjectByName(k?g[1]:g[0]),k?(g=d?d.scene.objectHash[g[0]]:null,a.url=g?g.data.param.videoUrl:a.url):g=d?d.scene.getObjectByName(g[1]):null;else if(k){if((g=d.scene.objectHash[a.video_holder])||(g=d.scene.dom.querySelector('*[data-guid="'+a.video_holder+'"]')),g&&g.data)a.url=g.data.param.videoUrl}else g=d.scene.getObjectByName(a.video_holder)}else{if(window.mugedaCss&&mugedaCss.magic&&(d=document.getElementById(mugedaCss.magic+
"stage")))g=a.video_holder,g=g.split("/").map(function(a){return"."+a}),(g=d.querySelectorAll(g.join(" ")))&&g.length&&(g=g[0])}else g=document.body;var h=this.createHTML5VideoTag(g,a);h.style.top=b+"px";h.style.left=c+"px";h.style.width=e;h.style.height=f;h.style.display="block";var i=h.querySelector("video");i.src=a.url;i.rawSrc=a.url;i.load();setTimeout(function(){if(a.showLoading)MugedaTools.message.show(null,{hideShade:true,parent:h,center:true}),i.loadingShown=true,i.ontimeupdate=function(){if(i.loadingShown)MugedaTools.message.close(),
i.loadingShown=false};a.event=="appear"&&(window.WeixinJSBridge?WeixinJSBridge.invoke("getNetworkType",{},function(){i.play();i.playing=true},false):document.addEventListener("WeixinJSBridgeReady",function(){WeixinJSBridge.invoke("getNetworkType",{},function(){i.play();i.playing=true})},false));i.play();i.playing=true},10)},playVideo:function(a){a=a||{};if(!a.video_url)return false;if(this.mraidReadyStatus!=1){var c=a.dom||document.querySelector('video[video-id="'+a.video_id+'"]');a.video_mode=="object"&&
a.video_id&&c&&c.rawSrc==a.video_url||this.playHTML5Video({url:a.video_url,id:a.video_id||"",name:a.video_name||"",mode:a.video_mode||"",video_object:parseInt(a.video_object,10),video_holder:a.video_holder,left:parseInt(a.video_left,10),top:parseInt(a.video_top,10),width:parseInt(a.video_width,10),height:parseInt(a.video_height,10),close_button:parseInt(a.video_close,10)==1,video_controls:parseInt(a.video_controls,10)==1,video_embed:parseInt(a.video_embed,10)==1,auto:parseInt(a.video_autoplay,10)==
1,event:a.event})}else mraid.playVideo(a.video_url)},stopVideo:function(){for(var a=document.querySelectorAll("div.mugedaVideoHolder"),c=0,b=a.length;c<b;c++){var e=a[c].querySelector("video");if(e)e.backSrc=e.src,e.backRawSrc=e.rawSrc,e.src="",e.rawSrc="",e.load();a[c]&&(a[c].style.display="none")}},controlVideo:function(a,c){var b=document.querySelector("#mugeda_video_"+a);if(b)if(c=="play")b.play();else if(c=="pause")b.pause();else{if(c=="stop")b.pause(),b.currentTime=0}else if((b=Mugeda.getMugedaObject?
Mugeda.getMugedaObject():null)&&b.scene)if(b=b.scene.objectHash[a]){var e=b.data.param;c==="play"&&MugedaMraid.playVideo({auto:e.videoAutoPlay,clickStatus:e.clickStatus,event_name:"",hidePlayIcon:e.hidePlayIcon,video_close:0,video_continue_audio:e.continueAudio,video_controls:e.hidePlayControls==1?0:1,video_holder:b.data.guid,video_left:0,video_mode:"object",video_name:e.name,video_embed:e.embedVideo,video_object:1,video_top:0,video_url:e.videoUrl})}},sendShortMessage:function(a){var c="sms:"+a.phone_number;
if(a.sms_body){var b=navigator.userAgent.toLowerCase().indexOf("android")>-1;c+=(b?"?":"&")+"body="+a.sms_body}window.open(c,"_self")},makePhoneCall:function(a){window.open("tel:"+a.phone_number,"_self")}};
Mugeda.getContentId=function(){var a="",c=0;if(window._mrmcp&&window._mrmcp.creative_id)a=window._mrmcp.creative_id,window._mrmcp.previewMode&&(c=3);else if(Mugeda&&Mugeda.data&&Mugeda.data.crid)a=Mugeda.data.crid,c=3;if(a==""&&/\/edit\/(\w+)\&?/.test(top.location.href))a=RegExp.$1,c=a.length<16?1:2;else if(a==""&&/id=(\w+)\&?/.test(window.location.search))c=3,a=RegExp.$1;return{crid:a,mode:c}};
MugedaBehavior={localCache:{},shakeHash:{},pause:function(){typeof Mugeda!="undefined"&&Mugeda.pause&&Mugeda.pause()},resume:function(a){typeof Mugeda!="undefined"&&Mugeda.resume&&Mugeda.resume(a)},nextPage:function(){typeof Mugeda!="undefined"&&Mugeda.nextPage&&Mugeda.nextPage()},prevPage:function(){typeof Mugeda!="undefined"&&Mugeda.prevPage&&Mugeda.prevPage()},gotoPage:function(a){typeof Mugeda!="undefined"&&Mugeda.gotoPage&&Mugeda.gotoPage(a)},disablePage:function(){typeof Mugeda!="undefined"&&
Mugeda.disablePage&&Mugeda.disablePage()},enablePage:function(){typeof Mugeda!="undefined"&&Mugeda.enablePage&&Mugeda.enablePage()},next:function(){typeof Mugeda!="undefined"&&Mugeda.next&&Mugeda.next()},previous:function(){typeof Mugeda!="undefined"&&Mugeda.previous&&Mugeda.previous()},gotoAndPlay:function(a){typeof Mugeda!="undefined"&&Mugeda.gotoAndPlay&&Mugeda.gotoAndPlay(a)},gotoAndStop:function(a){gotoAndPause(a)},gotoAndPause:function(a){typeof Mugeda!="undefined"&&Mugeda.gotoAndPause&&Mugeda.gotoAndPause(a)},
callback:function(a,c){var b=Mugeda.getMugedaObject?Mugeda.getMugedaObject():null,e=null;b&&(e=b.getCallback(c.name));!e&&window&&c.name&&c.name.length&&window[c.name]&&(e=window[c.name]);e&&e(a,c.key,c.value)},map:function(a){var c=a.map_key.replace(/(\n|\r)/g,"+"),b=a.map_address.replace(/(\n|\r)/g,"+"),e=navigator.userAgent.toLowerCase().indexOf("android")>-1,f=parseInt(a.map_type,10),d=function(){for(var a=document.querySelectorAll("div.mugedaVideoHolder"),c=0,b=a.length;c<b;c++)a[c]&&(a[c].style.display=
"none");(a=G("mugedaMap-mask"))?g(1):(a=document.createElement("div"),c=window._mrmcp&&_mrmcp.creative_path?_mrmcp.creative_path+"loading.gif":"/images/loading.gif",a.id="mugedaMap-mask",a.className="mugedaMapControl",a.innerHTML='<p id="mugedaMap-title"><a id="mugedaMap-back">\u8fd4\u56de</a>\u4f4d\u7f6e\u4fe1\u606f</p><div id="mugedaMap-con"></div><div id="mugedaMap-loading"><div class="spinner"></div><style>.mugedaMapControl {position:absolute;left:0;top:0;height:100%;width:100%;z-index:999999;}.mugedaMapMaskVisible {-webkit-transition:transform 1s;transform:translate3d(-100%, 0, 0);-webkit-transform:translate3d(-100%, 0, 0);}.mugedaMapControl #mugedaMap-title {position:fixed;height:44px;line-height:44px;width:100%;text-align:center;z-index:1;background:rgba(255,255,255,.8);margin:0;}.mugedaMapControl #mugedaMap-con {height:100%;width:100%;}.mugedaMapControl #mugedaMap-back {position:absolute;left:5px;display:inline-block;height:100%;width:40px;cursor:pointer;}.mugedaMapControl #mugedaMap-loading {position:absolute;width:100%;height:100%;line-height:100%;left:0;top:44px;display:none;background:#fff;z-index:2;}.mugedaMapControl .spinner {position:absolute;width:20px;height:30px;left:50%;top:50%;margin:-50px 0 0 -10px;background-image:url('+
c+');background-repeat:no-repeat;background-size:contain;}.mugedaMapControl .spinner:after {content: "\u52a0\u8f7d\u4e2d ...";position:absolute;width:80px;left:-25px;top:120%;}</style>',document.body.appendChild(a),(a=G("mugedaMap-back"))&&a.addEventListener("click",function(a){a.stopPropagation();g(0)},false))},g=function(a){var c=G("mugedaMap-mask");c&&c.classList.toggle("mugedaMapMaskVisible",!a)},k=function(a){var c=G("mugedaMap-loading");if(c)c.style.display=a?"block":"none"},h,i,t=function(a,
c,b,d){h||(h=new BMap.Map("mugedaMap-con"));h.centerAndZoom(b||"\u5317\u4eac",11);h.addControl(new BMap.MapTypeControl({mapTypes:[BMAP_NORMAL_MAP,BMAP_HYBRID_MAP]}));var b=new BMap.ScaleControl({anchor:BMAP_ANCHOR_TOP_LEFT}),e=new BMap.NavigationControl,g=new BMap.NavigationControl({anchor:BMAP_ANCHOR_TOP_RIGHT,type:BMAP_NAVIGATION_CONTROL_SMALL});h.addControl(b);h.addControl(e);h.addControl(g);i||(i=new BMap.LocalSearch(h,{renderOptions:{map:h,autoViewport:true},onSearchComplete:function(a){typeof d===
"function"&&d.call(h,a)}}));c&&a?i.searchNearby(c,a):i.search(c)},r=function(a,c,b){if(f===0){var e=["http://api.map.baidu.com/api?v=2.0&ak=FOm6cLbES9zjrtvcDYndkwSR","http://api.map.baidu.com/getscript?v=2.0&ak=FOm6cLbES9zjrtvcDYndkwSR"],c=decodeURIComponent(c),a=decodeURIComponent(a);d();k(1);for(var g=0,b=0,h=e.length;b<h;b++){var i=document.createElement("script");i.src=e[b];i.onload=function(){++g===h&&t(a,c,"",function(a){a.getNumPois()===0&&Mugeda.messageBox("\u62b1\u6b49\uff0c\u6ca1\u6709\u641c\u7d22\u5230\u76f8\u5173\u4fe1\u606f",
"alert");k(0)})};document.head.appendChild(i)}}else if(e="https://maps.google.com/maps?q="+(a+""+(c.length?"+near+"+c:""))+"&z=12",i=parseFloat((""+(/CPU.*OS ([0-9_]{1,5})|(CPU like).*AppleWebKit.*Mobile/i.exec(navigator.userAgent)||[0,""])[1]).replace("undefined","3_2").replace("_",".").replace("_",""))||false,b==1){if(b=document.getElementById("aMugedaGeoLocation"))b.href=e,e=document.createEvent("HTMLEvents"),e.initEvent("click",true,true),b.dispatchEvent(e)}else i&&i<6?window.location.href=e:
window.open(e,"_blank")};if(!e&&b.length==0&&navigator.geolocation){a=document.getElementById("aMugedaGeoLocation");if(!a)a=document.createElement("a"),a.id="aMugedaGeoLocation",a.style.display="none",a.href="",a.target="_blank",document.body.appendChild(a);navigator.geolocation.getCurrentPosition(function(a){b=a.coords.latitude+","+a.coords.longitude;r(c,b,1)})}else r(c,b)},popupForm:function(a,c){function b(a,c){if(a&&c)return a.querySelector("#"+c)}function e(a){if(window.localStorage&&window.localStorage.getItem)return unescape(localStorage.getItem(a)||
"");var c,b,d,e=document.cookie.split(";");for(c=0;c<e.length;c++)if(b=e[c].substr(0,e[c].indexOf("=")),d=e[c].substr(e[c].indexOf("=")+1),b=b.replace(/^\s+|\s+$/g,""),b==a.toLowerCase())return unescape(d);return""}function f(a,c){if(window.localStorage&&window.localStorage.getItem)try{localStorage.setItem(a,escape(c))}catch(b){console.info("Oops, localStorage full"),localStorage.clear(),localStorage.setItem(a,escape(c))}else{var d=new Date;d.setDate(d.getDate()+3);d=escape(c)+"; expires="+d.toUTCString();
document.cookie=a.toLowerCase()+"="+d}}function d(a){var c=document.querySelector(".MugedaStage")?null:G("viewbox")||G("frame");if(c)c.style.display=a?"":"none";return c?true:false}function g(a){if(c){var b=function(a,c){Array.prototype.forEach.call(a,function(a,b){c(a,b)})};b(a.querySelectorAll(".popupFormInputBox input,.popupFormInputBox textarea"),function(a){a.value=""});b(a.querySelectorAll(".popupFormRadioList input,.popupFormCheckbox input"),function(a){a.checked=false});b(a.querySelectorAll(".popupFormSelectList select"),
function(a){a.value=a.querySelector("option").getAttribute("value")})}else if(b=a.querySelector("form"),b.style.bottom=-b.offsetHeight+"px",a.style.background="rgba(0,0,0,0)",setTimeout(function(){a.parentNode&&a.parentNode.removeChild(a)},500),d(1)&&(document.body.style.overflowY="hidden",isMobile()))document.body.style.height="100%"}var k=a.openTarget=="default"||a.openTarget=="frame"||a.openTarget=="page";if(a&&!(a.openTarget=="callback"&&!a.callback||a.openTarget!="callback"&&a.openTarget!="customizable"&&
!k&&!a.url)){var k=document.documentElement.clientWidth,h=document.documentElement.clientHeight,i=[],t=function(c,b){var b=b||{},d=b.detail,e=b.form||(d?d.form:null),d={item:d,form:e,title:a.title,hideItem:function(a){e&&e.elements[a]&&(e.elements[a].parentNode.style.display="none")},showItem:function(a){e&&e.elements[a]&&(e.elements[a].parentNode.style.display="block")}},b=document.createEvent("Events");b.initEvent(c,true,true);b.detail=d;window.dispatchEvent(b)};window.addEventListener("_mugedaFormChanged",
function(a){t("mugedaFormChanged",a)});var r=a.items||[];window.popupFormFields=r;if(!a.html){var j="";c?(j+='<div class="popupFormContent">',a.title&&(j+='<div align="center" class="popupFormTitle"><h2>'+a.title+"</h2></div>")):(j+='<div align="center" class="popupFormTitle">',j+='<div class="title-col-2" align="center"><input type="button" value="'+a.cancelName+'" class="popupFormCancel" id="popupFormCancel"></div>',j+='<div class="title-col-6" align="center"><h2>'+(a.title||"&nbsp;")+"</h2></div>",
j+='<div class="title-col-2" align="center"><input id="actionButton" type="button" value="'+a.submitName+'" class="popupFormSubmit"></div>',j+="</div>",j+='<div class="popupFormContent">');var m=navigator.userAgent.toLowerCase(),p=m.indexOf("android")>-1,q=parseFloat(m.slice(m.indexOf("android")+8)),l="",z=0,y={phone:"tel",input:"text"};p&&q<3&&(l="-webkit-transform: scale(2,2);-webkit-transform-origin:center center;");for(var B=c?"":":",m=0;m<r.length;m++){var n=r[m],x=(n.value||"").trim();if(x){for(var x=
x.split("\n"),u=[],v=0;v<x.length;v++){var I=x[v].split("("),A=I[0],I=(I[1]||"").replace(/\)$/,"")||A,F=["FORMID",I,m,v].join("_");u[v]={id:F,text:A,value:I}}x=u}F='id="popupFormField_'+m+'"';switch(n.type){case "radio":j+="<div "+F+' class="popupFormRadioList">';n.description&&(j+='<label class="inputlabel">'+n.description+(n.required?"*":"")+B+"</label>");j+='<div class="mformradio">';for(v=0;v<x.length;v++)u=x[v],A=e(u.id),j+='<label><input onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" type="radio" name="'+
n.id+'" value="'+u.value+'" id="'+u.id+'" '+(A=="true"?"checked=checked":"")+" ><span "+(v==x.length-1?"":" style='border-right:1px solid "+a.background+"'")+">"+u.text+"</span></label>",i[u.id]=u.id;j+="</div></div>";break;case "checkbox":j+="<div "+F+' class="popupFormCheckbox">';n.description&&(j+='<label class="inputlabel">'+n.description+(n.required?"*":"")+B+"</label>");j+='<div class="mformcheck">';j+=n.rangeType==="vertical"?"<table>":"";for(v=0;v<x.length;v++)u=x[v],A=e(u.id),j+=n.rangeType===
"vertical"?'<tr><td><input type="checkbox" value="'+u.value+'" id="'+u.id+'" '+(A=="true"?"checked=true":"")+' ></td><td><label for="'+u.id+'" >'+u.text+"</label></td></tr>":'<input onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" type="checkbox" name="'+n.id+'" value="'+u.value+'" id="'+u.id+'" '+(A=="true"?"checked=true":"")+' ><label for="'+u.id+'" >'+u.text+"</label>",i[u.id]=u.id;p&&q<
3&&n.rangeType!="vertical"&&(z=6);j+=n.rangeType==="vertical"?"</table>":"";j+="</div></div>";break;case "select":j+="<div "+F+' class="popupFormSelectList">';n.description&&(j+='<label class="inputlabel text">'+n.description+(n.required?"*":"")+B+"</label>");j+='<select class="text" onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" name="'+n.id+'" id="'+("_map_"+n.description)+'">';j+='<option value="">'+
n.description+"</option>";A=e(n.description);for(v=0;v<x.length;v++)u=x[v],j+='<option value="'+u.value+'" '+(A==u.value?"selected=selected":"")+">"+u.text+"</option>";j+="</select>";j+="</div>";i[n.description]="_map_"+n.description;break;case "textarea":j+="<div "+F+' class="popupFormInputBox">';j+='<label class="inputlabel inputlabel_area">'+n.description+(n.required?"*":"")+B+'</label><textarea name="'+n.id+'" id="_mcp_'+escape(n.description)+'" rows="4" onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" style="resize:none; height:48px;">'+
(n.value.length?n.value:e(n.description))+"</textarea>";j+="</div>";i[n.description]="_mcp_"+escape(n.description);break;default:j+="<div "+F+' class="popupFormInputBox">',j+='<label class="inputlabel text">'+n.description+(n.required?"*":"")+B+'</label><input class="text" name="'+n.id+'" id="_mcp_'+escape(n.description)+'" type="'+(y[n.type]||n.type)+"\" onchange=\"var event = document.createEvent('Events');event.initEvent('_mugedaFormChanged', true, true);event.detail = this;window.dispatchEvent(event);\" value=\""+
(e(n.description)||n.value)+'" '+(c?'placeholder="'+n.description+'"':"")+">",j+="</div>",i[n.description]="_mcp_"+escape(n.description)}}c&&(j+='<div class="popupFormBtn"><input type="button" value="'+a.cancelName+'" class="popupFormCancel" id="popupFormCancel">',j+='<input id="actionButton" type="button" value="'+a.submitName+'" class="popupFormSubmit"></div>');j+="</div>";a.html=j}delete this.popupFormDiv;var o=this.popupFormDiv;if(!o){m=function(b){var b=b||".popupForm",d=1;if(/^rgba\(\d+,\s\d+,\s\d+,\s([0-9.]+)\)$/.exec(a.background))d=
RegExp.$1;d="<style>"+b+" {width:100%;font-size:"+a.fontSize+'px;font-family:Tahoma,"\u5fae\u8f6f\u96c5\u9ed1",Arial, SimHei;}'+b+' * {font-family:Tahoma,"\u5fae\u8f6f\u96c5\u9ed1",Arial, SimHei;}'+b+" form{position:absolute;width:100%;background-color:"+a.background+";}"+b+" *{margin:0;box-sizing:border-box;-webkit-appearance: none; -moz-appearance: none; appearance: value;}"+b+" .inputlabel{width:33%;height:28px;font-size:"+a.fontSize+"px;line-height:28px;display:inline-block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;vertical-align:top;color:#000;}"+
b+" span{color:#333;}"+b+" label{color:#000;}"+b+" #popupFormField_0{padding-top:16px;}"+b+" .popupFormMask {position:absolute;left:0;top:0;width:100%;height:100%;background-color: "+a.background+"}"+b+" .popupFormContent {padding-bottom:16px; background-color:#fff;opacity:"+d+";}"+b+" .popupFormTitle {width:100%;padding:20px 0;overflow:hidden;background-color: "+a.background+"}"+b+" h2 {font-weight:normal;font-size:"+(2+parseInt(a.fontSize))+"px;color:"+a.color+";}"+b+" h3{text-align:left;font-size:"+
a.fontSize+"px; font-weight: normal;color:"+a.color+";}"+b+" .popupFormInputBox{padding:8px 16px;text-align:left;}"+b+" .popupFormInputBox input, .popupFormInputBox textarea, .popupFormSelectList select{width:67%;height:28px;border:1px solid "+a.background+";font-size:"+a.fontSize+"px;padding:0;padding-left:8px;vertical-align:top;border-radius:2px;}"+b+" .popupFormSelectList{padding:8px 16px 0;}"+b+" .popupFormRadioList{padding:8px 16px 0;}"+b+" .popupFormCheckbox{padding:8px 16px 0;}"+b+" .popupFormTitle input{border-width:0;cursor:pointer;font-size:"+
a.fontSize+"px;color:"+a.color+"}"+b+" .popupFormSubmit{border:none;background:none}"+b+" .popupFormCancel{background:none;border:none;}"+b+" .popupFormRadioList input{margin:0 5px 0 8px;}"+b+" .popupFormRadioList label{vertical-align:top;}"+b+" .mformradio {background-color:#EFEFEF;border:1px solid "+a.background+";overflow:hidden;display:inline-block;}"+b+" .mformradio label{float:left; min-width:48px;position:relative;}"+b+" .mformradio label span{text-align:center;padding:6px 8px;display:block;}"+
b+" .mformradio label input{position:absolute;width:100%;height:100%;margin:0;border:0;opacity:0;}"+b+" .mformradio input:checked + span{background-color:"+a.background+";color:#F7F7F7;}"+b+" .mformcheck{margin:0 0 8px;display:inline-block;}"+b+" .mformcheck input{"+l+"width:24px;height:24px;background-color:#EFEFEF;border:1px solid "+a.background+";vertical-align:middle;margin:3px 2px;}"+b+" .mformcheck input:checked{background-color:"+a.background+";}"+b+" .popupFormTitle .title-col-2 {float:left;width:20%;padding:0 ;text-align:center;}"+
b+" .popupFormTitle .title-col-6 {float:left;width:60%;padding:0 ;}"+b+" .popupFormTitle .title-col-2 input {font-size:"+(2+parseInt(a.fontSize))+"px;}"+b+" .mformcheck label{vertical-align:"+z+"px;font-size:"+a.fontSize+"px;padding-top:0;padding-left:4px;padding-right:8px;}";c&&(d+=b+" .popupFormBtn {width:100%;padding:20px 0 0 0;text-align:center;}",d+=b+" .popupFormSubmit {width:90px;height:30px;color:"+a.color+";background-color:"+a.background+"}",d+=b+" .popupFormCancel {width:90px;height:30px;margin-right:15px;color:"+
a.color+";display:none;background-color:"+a.background+"}");d+="</style>";return d};if(!o){var J=a.openTarget=="backend"?"popupFormIframe":"_"+a.openTarget,o=document.createElement("div");o.style.display="none";o.className=c?"popupForm2":"popupForm";var C="";if(c)var D=function(b){for(var c={l:48,r:200},d=0,e=0,g=b.length;e<g;e++){for(var f=b[e],h=f.description.length,i=0,j=0;j<h;j++)i+=f.description[j].match(/[\u3400-\u9FBF]/)?2:1;d=Math.max(d,i)}d=d>8?8:d;b=a.fontSize*(d-4);d>4&&d<=8&&(c.l+=b,c.r-=
b);return c}(r),C=m(".popupForm2");else C=m();o.innerHTML='<form method="'+a.method+'" target="'+J+'" autocomplete="on"></form><iframe name="popupFormIframe" id="popupFormIframe" style="display:none"></iframe>'+C;!c&&!a.isCss?document.body.appendChild(o):(a.hwObj=D,a.iframeDiv=o,a.parentDom&&a.parentDom.appendChild(a.iframeDiv));this.popupFormDiv=o;o.form=o.childNodes[0];o.form.onclick=function(){};self=this;c||o.addEventListener(isMobile()?"touchend":"mouseup",function(a){if(!window.cardFrame){if(a.target==
o)g(o),self.popupFormDiv=null,a.stopPropagation();var b=a.target.nodeName.toLowerCase(),c=(a.target.type||"").toLowerCase();["input","textarea","select"].indexOf(b)>=0&&c!="checkbox"&&c!="submit"&&(a.target.focus(),p&&setTimeout(function(){a.target.scrollIntoView();a.target.scrollIntoViewIfNeeded&&a.target.scrollIntoViewIfNeeded()},500),a.stopPropagation());c=="button"&&a.stopPropagation()}});C=function(){function d(){var e=[],f=r;if(!c)f=window.popupFormFields;for(var h=0;h<f.length;h++){var i=f[h],
j=b(o,"popupFormField_"+h),k="",l=j.querySelectorAll("select");l.length==0&&(l=j.querySelectorAll("textarea"),l.length==0&&(l=j.querySelectorAll("input")));if(l.length==1)k=l[0].value||"";else if(l.length>1){for(var k=[],m=0;m<l.length;m++)if(j=l[m],j.checked&&(k.push(j.value),j.type=="radio"))break;k=k.join(",")}if(i.required&&!k){Mugeda.messageBox((i.description||"item")+" required");l[0].focus();return}if(k)switch(i.type){case "phone":if(!/^\d+$/.test(k)){Mugeda.messageBox((i.description||"Phone number")+
" required");l[0].focus();return}break;case "email":if(!/^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/.test(k)){Mugeda.messageBox((i.description||"Email")+" required");l[0].focus();return}}a.openTarget==="default"?e.push(encodeURIComponent(i.description+"("+i.id+")")+"="+encodeURIComponent(k||"")):e.push(encodeURIComponent(i.id)+"="+encodeURIComponent(k||""))}if("popupFormIframe"==J)G("actionButton").value=a.pendingName;e=e.join("&");f=a.url+"?"+e;a.loadFinished=function(){g(o);self.popupFormDiv=
null};if(a.openTarget=="customizable")f={callback:function(b){a.msg?Mugeda.messageBox(a.msg,"alert",function(){window.open(b,"_self")}):window.open(b,"_self")},cancel:false},window.MugedaCard&&MugedaCard.finalizeCustomParameters&&MugedaCard.finalizeCustomParameters(e,f),a.loadFinished();else if(a.openTarget=="default"||a.openTarget=="page"||a.openTarget=="frame"||a.openTarget=="callback"){h="";f=0;if(window._mrmcp)h=window._mrmcp.creative_id||"",window._mrmcp.previewMode&&(f=3);else if(Mugeda&&Mugeda.data&&
Mugeda.data.crid)h=Mugeda.data.crid;if(h==""&&/\/edit\/(\w+)\&?/.test(top.location.href))h=RegExp.$1,f=h.length<16?1:2;else if(h==""&&/id=(\w+)\&?/.test(window.location.search))f=3,h=RegExp.$1;i=function(a,b,c){var c=c||"post",d=document.createElement("form"),e=document.createElement("iframe");d.setAttribute("method",c);d.setAttribute("action",a);a="__iframe"+Math.random()*1E4;e.setAttribute("id",a);e.setAttribute("name",a);d.setAttribute("target",a);e.style.width=0;e.style.height=0;e.style.display=
"none";e.addEventListener("load",function(){});a=0;for(c=b.length;a<c;a++){var f=b[a].split("="),g=f[0],f=f[1],h=document.createElement("input");h.setAttribute("type","hidden");h.setAttribute("name",g);h.setAttribute("value",f);d.appendChild(h)}document.body.appendChild(d);document.body.appendChild(e);d.submit()};if(h&&/^[a-zA-Z0-9\-\_\.]+\.(mugeda|mgd5|h5mc|h5mgd|imugeda|mgdh5|hubpd)\.com$/.test(window.location.hostname))window._mrmcp=window._mrmcp||{},i(_mrmcp.saveFormUrl||"//weika.mugeda.com/server/cards.php/saveform",
(e+"&crid="+h+"&mode="+f).split("&")),a.msg&&Mugeda.messageBox(a.msg);a.openTarget=="callback"?a.callback&&window[a.callback]?(f={callback:function(){a.msg&&Mugeda.messageBox(a.msg)},cancel:false},window[a.callback](e,f),MugedaTracker.fireEvent({category:"interaction",action:"form",label:"",value:a.id?parseInt(a.id,36):0}),f.cancel!==true&&f.callback()):console.log("No callback function found. Skipping..."):a.openTarget=="frame"?a.callback&&a.callback():a.openTarget=="page"&&a.callback&&a.callback();
a.loadFinished()}else try{window.open(f,J),G("popupFormIframe").onload=function(){a.loadFinished();MugedaTracker.fireEvent({category:"interaction",action:"form",label:"",value:a.id?parseInt(a.id,36):0});a.msg&&Mugeda.messageBox(a.msg)}}catch(p){a.loadFinished(),Mugeda.messageBox("Form submission failed. Please try again. ")}}o.querySelector("#popupFormIframe").onload=null;for(n in i){var e=document.getElementById(i[n]);e&&(e.type=="checkbox"||e.type=="radio"?f(n,e.checked):f(n,e.value))}q<3?d():setTimeout(d,
200);return false}}o.style.display="";o.form.innerHTML=a.html;if(a.id)o.form.id=a.id;var K=isMobile()?"touchstart":"click";o.form.querySelector("input[id=actionButton]").addEventListener(K,C,false);o.style.display="";o.style.visibility="hidden";setTimeout(function(){t("mugedaFormInitialized",{form:o.form});o.style.visibility="visible"},200);setTimeout(function(){b(o,"popupFormCancel").addEventListener(K,function(){g(o);self.popupFormDiv=null},false)},500);D=o.querySelectorAll(".popupFormInput");for(m=
0;m<D.length;m++)C=D[m],C.onfocus=onInputFocus,C.onblur=onInputBlur;var w;a.target?w=a.target.getBoundingClientRect():(D=Mugeda.getMugedaObject?Mugeda.getMugedaObject():null)&&a.isCss?(k=D.adaption,w={left:Math.max(0,(window.Mugine?1:-1)*k.marginLeft),top:window.Mugine?0:Math.max(0,(window.Mugine?1:-1)*k.marginTop),width:Math.min(k.width,D.width),height:Math.min(k.height,D.height)}):w={left:0,top:0,width:k,height:h};document.body.style.overflowY="auto";if(d()){if(o.style.marginLeft=Math.max(2,w.left+
document.documentElement.scrollLeft+(w.width-o.offsetWidth)/2)+"px",o.style.marginTop=Math.max(2,w.top+document.documentElement.scrollTop+(w.height-o.offsetHeight)/2)+"px",o.style.marginBottom="32px",o.offsetHeight+32>document.documentElement.scrollHeight&&(o.style.marginTop=parseInt(window.getComputedStyle?getComputedStyle(o).marginTop:o.currentStyle.marginTop)+32+"px",isMobile()))document.body.style.height=o.offsetHeight+64+"px"}else if(o.style.position="relative",o.style.left=w.left+"px",o.style.top=
w.top+"px",Math.max(2,w.top+(w.height-o.offsetHeight)/2),Math.max(2,w.left+(w.width-o.offsetWidth)/2),!c){var H=o.querySelector("form");H.style.bottom="-9999px";o.style.overflow="hidden";setTimeout(function(){o.style.background="rgba(0,0,0,0)";o.style.width=w.width+"px";o.style.height="100%";H.style.webkitTransition="none";H.style.bottom=-H.offsetHeight+"px";setTimeout(function(){H.style.webkitTransition="all 500ms";H.style.bottom="0px";H.style.overflowY="auto";!c&&(o.style.background="rgba(0,0,0,0.3)")},
1)},1)}}}},getPopupFormHeight:function(a){for(var c=a.items,b=0,e=0,f=c.length;e<f;e++){var d=c[e];switch(d.type){case "input":case "phone":case "email":b+=44;break;case "textarea":b+=64;break;case "radio":b+=48;break;case "checkbox":d=d.value.split("\n").length;b+=32*d+8;break;case "select":b+=36;break;default:b+=44}}a.title&&(b+=60);b+=8;b+=50;b+=16;return b},processAction:function(a,c,b,e){var f=true;if(a.type=="pause")this.pause(a.param);else if(a.type=="play")this.resume(1);else if(a.type=="next")this.next();
else if(a.type=="previous")this.previous();else if(a.type=="nextPage")this.nextPage();else if(a.type=="prevPage")this.prevPage();else if(a.type=="disablePage")this.disablePage();else if(a.type=="enablePage")this.enablePage();else if(a.type=="gotoPage"){var d=a.param&&a.param.page_number?a.param.page_number:a.param,g=typeof d=="string"?d.split(";"):[];g.length>1&&(d=g[Math.floor(Math.random()*g.length)]);d=parseInt(d);this.gotoPage(d)}else if(a.type=="callback")this.callback(a.object,a.param);else if(a.type==
"map")this.map(a.param);else if(a.type=="gotoAndPlay")d=a.param&&a.param.frame_number?a.param.frame_number:a.param,g=typeof d=="string"?d.split(";"):[],g.length>1&&(d=g[Math.floor(Math.random()*g.length)]),d=parseInt(d),isNaN(d)&&(d=a.param&&a.param.frame_name?a.param.frame_name:"",d=Mugeda.mapFrameNameId[d],d=parseInt(d)+1),this.gotoAndPlay(d);else if(a.type=="gotoAndPause"||a.type=="gotoAndStop")d=a.param&&a.param.frame_number?a.param.frame_number:a.param,g=typeof d=="string"?d.split(";"):[],g.length>
1&&(d=g[Math.floor(Math.random()*g.length)]),d=parseInt(d),isNaN(d)&&(d=a.param&&a.param.frame_name?a.param.frame_name:"",d=Mugeda.mapFrameNameId[d],d=parseInt(d)+1),this.gotoAndPause(d);else if(a.type=="call")MugedaMraid.makePhoneCall(a.param);else if(a.type=="sms")MugedaMraid.sendShortMessage(a.param);else if(a.type=="email")MugedaMraid.sendEmail(a.param);else if(a.type=="video")a.param.event=c,MugedaMraid.playVideo(a.param);else if(a.type=="stopVideo")MugedaMraid.stopVideo(a.param);else if(a.type==
"audio")a.param.event=c,f=a.restart,window.Mugeda&&Mugeda.getMugedaObject&&(c=Mugeda.getMugedaObject(),d=Math.floor(c.scene.currentId),a.unit&&a.unit.frameStart==d&&(f=true)),f=MugedaMraid.playAudio(a.param,f);else if(a.type=="picture")MugedaMraid.savePicture(a.param);else if(a.type=="calendar")MugedaMraid.addCalendarEvent(a.param);else if(a.type=="expand")MugedaMraid.expand(a.param.url,0,a.param);else if(a.type=="resize")MugedaMraid.expand("",1,a.param);else if(a.type=="stopAudio")Mugeda.stopAudio&&
Mugeda.stopAudio(a.param);else if(a.type=="stopAllAudio")Mugeda.stopAudioAll&&Mugeda.stopAudioAll();else if(a.type=="submitForm"){var k=a.param,c=a.mugeda,g=k.submit_object,h=k.submit_target||0;window._mrmcp=window._mrmcp||{};var k=h==0?_mrmcp.saveFormUrl||"//weika.mugeda.com/server/cards.php/saveform":k.submit_url,i="",h=0;if(window._mrmcp&&window._mrmcp.creative_id)i=window._mrmcp.creative_id,window._mrmcp.previewMode&&(h=3);else if(Mugeda&&Mugeda.data&&Mugeda.data.crid)i=Mugeda.data.crid,h=3;if(i==
""&&/\/edit\/(\w+)\&?/.test(top.location.href))i=RegExp.$1,h=i.length<16?1:2;else if(i==""&&/id=(\w+)\&?/.test(window.location.search))h=3,i=RegExp.$1;if(i&&g){for(var g=g.split(","),i="crid="+i+"&mode="+h,h={},t=0,r=0;r<g.length;r++){var j=g[r]||"",m=j.split("_"),p;if(m&&m.length>1){var q=c.scene.getObjectByName(m[0]);q&&(p=q.scene.getObjectByName(m[1]))}else p=c.scene.getObjectByName(j);if(p)if(p.data.type===2041){if(d=p.data.param.name)if(m=p.data.param.required,j=p.dom.querySelector("input:checked"),
m===1&&!j){Mugeda.messageBox("\u8bf7\u9009\u62e9\u3010"+d+"\u3011\uff0c\u8be5\u9879\u4e0d\u80fd\u4e3a\u7a7a\u3002");return}else h[d]=j?j.value:"",t++}else if(p.data.type===2038){if(d=p.data.param.name)if(m=p.data.param.required,j=document.querySelectorAll("input[name="+d+"]:checked"),m===1&&!j.length){Mugeda.messageBox("\u8bf7\u9009\u62e9\u3010"+d+"\u3011\uff0c\u8be5\u9879\u4e0d\u80fd\u4e3a\u7a7a\u3002");return}else{for(var m=[],q=0,l=j.length;q<l;q++)m.push(j[q].value);h[d]=m.length?m.join(","):
"";t++}}else if(p.data.type===2039)if(m=p.data.param.required,q=unescape(p.data.param.textContent),l=p.dom.querySelector("option:checked"),m===1&&l&&l.innerText===q){Mugeda.messageBox("\u8bf7\u9009\u62e9\u3010"+q+"\u3011\uff0c\u8be5\u9879\u4e0d\u80fd\u4e3a\u7a7a\u3002");return}else i+=l?"&"+j+"="+(l.value!==q?l.value:""):"&"+j+"=",t++;else{q=p?p.text||"":"";q.indexOf("#")&&(q=q.replace(/\#/g,""));var l=p.data.param.inputType,z={tel:"^\\d+$",email:'^(([^<>()\\[\\]\\\\.,;:\\s@"]+(\\.[^<>()\\[\\]\\\\.,;:\\s@"]+)*)|(".+"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$',
date:"",time:"",number:"^\\d+$"},m=p.data.param.required;if(m===1&&!q.length){Mugeda.messageBox("\u8bf7\u9009\u62e9\u3010"+p.data.param.name+"\u3011\uff0c\u8be5\u9879\u4e0d\u80fd\u4e3a\u7a7a\u3002");return}else if(q.length&&(m=z[l])&&!RegExp(m).test(q)){Mugeda.messageBox("\u3010"+p.data.param.name+"\u3011\u7684\u5185\u5bb9\uff08"+q+"\uff09\u7684\u683c\u5f0f\u4e0d\u6b63\u786e\u3002\u8bf7\u68c0\u67e5\u540e\u91cd\u8bd5\u3002");return}j&&(j=j.replace(/#/g,"_"),i+="&"+j+"="+q,t++)}}if(t==0)return;k+="?"+
i;if(Object.keys(h).length>0)for(d in h)d.indexOf("#")?(c=h[d],d=d.replace(/#/g,"_"),k+="&"+d+"="+c):k+="&"+d+"="+h[d];if(a.extraData)for(var y in a.extraData)k+="&"+y+"="+a.extraData[y];MugedaTools.message.show("\u6b63\u5728\u63d0\u4ea4");ajaxHelper({url:k,type:"jsonp",jsonp_callback:"form_callback",success:function(a){MugedaTools.message.close();e&&e(a)},error:function(a){MugedaTools.message.close();e&&e({status:a.status})}})}}d="actoin_type="+a.type+"&refid="+(new Date).getTime();for(item in a.param)d+=
"&"+item+"="+a.param[item];f&&b&&a.param.event_name&&MugedaTracker.fireEvent({category:"interaction",action:a.param.event_name,label:d,value:0})},processCloseButton:function(a,c){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var b=c,e=null;if(!b)try{window!=window.parent?(b=window.parent.document,e=window.frameElement):b=document}catch(f){b=document}if(b){var d=null;try{d=window.parent.document,d.getElementById("mugeda_expanded")||d.createElement("div")}catch(g){return}var k=a||_mrmcp.display_mode,
h=MugedaMraid.mraidReadyStatus==1?mraid.getPlacementType():"default",i=b.getElementById("mugeda_close_button");if(!i)i=b.createElement("img"),i.id="mugeda_close_button",i.style.cursor="pointer",i.style.zIndex=99999,i.style.display="block",i.style.position="fixed",i.style.right="0",i.style.top="0",i.addEventListener("click",function(){if(MugedaMraid.mraidReadyStatus!=1){b.body.removeChild(i);k=="interstitial"&&e&&e.parentNode.removeChild(e);var a=b.getElementById("mugeda_expanded");a&&b.body.removeChild(a)}}),
b.body.appendChild(i);if(h=="interstitial"||k=="auto"||k=="resize"||k=="expand"||k=="interstitial")i.src=(_mrmcp.creative_path||"")+"close_button.png",i.onerror=function(){i.style.display="none"},i.onload=function(){i.style.display=h=="interstitial"||k!="auto"?"block":"none"}}},setupMobileActionCallback:function(a){MugedaBehavior.actionCallback=a},setupMobileActions:function(a,c,b){function e(a){var b=navigator.userAgent.toLowerCase().indexOf("android")>-1,d=b?15:20,e=b?5:10,t=function(a,g,j,m){if(Math.sqrt(a*
a+g*g+j*j)>=(m?d:e)){a=(new Date).getTime();g=a-(MugedaBehavior.lastHitTime||0);if(!MugedaBehavior.lastHitTime||g>200)MugedaBehavior.shakeNum++,MugedaBehavior.lastHitTime=a;else if(g>1E3)MugedaBehavior.shakeNum=0;if(MugedaBehavior.shakeNum>=(b?1:2)){for(var t in MugedaBehavior.shakeHash){a=MugedaBehavior.shakeHash[t];for(g=0;g<a.length;g++)info=a[g],j=info.object,j=j.displayObject?j.displayObject.realVisible:true,info.callback&&j&&(MugedaBehavior.processAction(info.behavior,info.behavior.event,true),
info.callback())}MugedaBehavior.actionCallback&&MugedaBehavior.actionCallback(f,c.event);MugedaBehavior.shakeNum=0}}},r=0,j=0,m=0;if(a.acceleration===null||a.acceleration.x===void 0||a.acceleration.y===void 0||a.acceleration.z===void 0||a.acceleration.x===null||a.acceleration.y===null||a.acceleration.z===null){if(a.accelerationIncludingGravity)r=a.accelerationIncludingGravity.x,j=a.accelerationIncludingGravity.y,m=a.accelerationIncludingGravity.z,t(r,j,m,1)}else r=a.acceleration.x,j=a.acceleration.y,
m=a.acceleration.z,t(r,j,m,0)}var f=a.dataRef||a.aniData;isMobile();isMobile();isMobile();if(c.event=="shake"&&window.DeviceMotionEvent){if(!window.mugedaShakeHooked)MugedaBehavior.shakeNum=0,window.addEventListener("devicemotion",e,false),window.mugedaShakeHooked=true;var d=a.aniData?a.aniData.guid:null;d&&(MugedaBehavior.shakeHash[d]||(MugedaBehavior.shakeHash[d]=[]),MugedaBehavior.shakeHash[d].push({object:a,callback:b,behavior:c}))}}};
MugedaTracker={fireEvent:function(a){if(!window.location||!window.location.host){var a=(_mrmcp.track_bot||"//cdn.mugeda.com/media/pages/track/track_20131030.html")+"?"+(_mrmma_var1||"var1=none")+"&"+(_mrmma_var2||"var2=none")+"&category="+a.category+"&action="+a.action+"&label="+encodeURIComponent(a.label)+"&value="+a.value+"&noninteraction="+a.noninteraction,c=document.createElement("iframe");c.id=_mrmcp.creative_id;c.src=a;c.style.display="none";c.style.width="1px";c.style.height="1px";document.body.appendChild(c)}else if(this.fireGAEvent(a.category,
a.action,a.label,a.value,a.noninteraction),this.fireMUEvent(a.category,a.action,a.label,a.value),window.mugedaGetCustomTracker&&(c=window.mugedaGetCustomTracker())){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var b=_mrmcp.custom_params,e=_mrmma_tags;b&&b.indexOf("%CUSTOMPARAM%")<0&&(e+="&"+b);c(e,a.category,a.action,a.label,a.value)}},fireGAEvent:function(a,c,b,e,f){typeof _gaq!="undefined"&&(_gaq.push(["_trackEvent",a,c,b,e,f]),typeof _ga_mugeda_use_custom!="undefined"&&_gaq.push(["custom._trackEvent",
a,c,b,e,f]))},fireMUEvent:function(a,c,b,e){typeof _mugeda_tracker!="undefined"&&_mugeda_tracker.trackEvent({action:c,category:a,label:b,value:e})}};
function mraidReady(){parseFloat(mraid.getVersion())-0.999>0?(MugedaMraid.mraidReadyStatus=1,_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp,_mrmcp.display_mode&&(mraid.useCustomClose(true),MugedaBehavior.processCloseButton()),mraid.addEventListener("error",function(){}),mraid.addEventListener("stateChange",function(){var a=mraid.getState();MugedaMraid.setMraidState(a)}),mraid.addEventListener("sizeChange",function(){})):console.log("mraidReady is called, but with no correct version (>= 1.0) supported.")}
var mraidReadyTimeout,mraidTimeOut=100,mraidCounter=0;function readyListener(){typeof mraid==="undefined"?(mraidCounter++,mraidCounter<mraidTimeOut&&(mraidReadyTimeout=setTimeout(readyListener,100))):mraid.getState()==="loading"?mraid.addEventListener("ready",mraidReady):mraidReady()}readyListener();
try{var htmlDoc=document.getElementsByTagName("head").item(0),js=document.createElement("script"),s="mraid.js";js.setAttribute("type","text/javascript");js.setAttribute("src",s);htmlDoc.appendChild(js);js.onload=function(){};js.onerror=function(){}}catch(e$$26){alert(e$$26.toString())}
function genSessionId(a){for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=Number(+new Date).toString(36),e=0,f="",d=c.length;e<a;e++)f+=c[Math.floor(Math.random()*d)];return b+f.toLowerCase()}
Mugeda.playEmbeddedVideo=function(a){a=a.target.parentElement;a.style.display="none";for(var c=0;c<a.parentElement.children.length;c++)a.parentElement.children[c].setAttribute("contenteditable","false");var b=a.previousSibling;b.play();b.onclick=function(){b.controls=b.paused?false:true;b.paused?b.play():b.pause()};if(navigator.userAgent.match(/mqqbrowser.*tbs/i)){for(var e=null;;)if(a=a.parentElement,a.className.indexOf("mugeda_richText_content")>=0){e=a.parentElement;break}else if(a==document.body)break;
var a=e.scrollTop,f=document.createElement("div");f.className="qbrowser_workaround";f.style.position="absolute";f.style.width="1px";f.style.height="1px";f.style.left=0;f.style.top=a+"px";e.appendChild(f);if(e)e.onscroll=function(){f.style.top=e.scrollTop+"px"}}};
Mugeda.DataStats={init:function(a){this.isPreview=location.pathname==="/client/preview_css3.html"&&/mugeda.com$/.test(location.host);if(!this.isPreview){this.viewId=function(){var a=Math.random().toString().substr(2,4)+""+(new Date-new Date("2012/1/1"));return Number(a).toString(36)}();this.crid=window._mrmcp.creative_id||Mugeda.data.crid||null;this.currentPageId=a.indexPageId;this.lockTime=false;var c=this.getCookie("msuid");c||(c=genSessionId(32),this.setCookie("msuid",c,3650));this.msuid=c;var b=
localStorage||window.localStorage||null;if(b){for(c=0;c<b.length;c++){var e=b.key(c);if(e.indexOf("leaveData_")>-1){var f=localStorage.getItem(e);if(f){var d={crid:null,viewId:null,pages:[],media:[]},f=JSON.parse(f);d.pages.push(f.pages);d.crid=f.crid;d.viewId=f.viewId;this.uploadData(d,function(){b.removeItem(e)})}}}this.videoHash={};this.statData={crid:this.crid,viewId:this.viewId,pages:[]};this.entry({type:"loadTime",indexPageId:a.indexPageId});this.bindTimer()}}},bindTimer:function(){var a=this;
a.second=1;setInterval(function(){if(!a.lockTime){var c=a.getCurrentPage();a.second==10?(c.stayTime+=1E3,c={crid:a.crid,viewId:a.viewId,pages:[{id:a.currentPageId,stayTime:c.stayTime}]},a.second=1,a.uploadData(c)):(c.stayTime+=1E3,localStorage.setItem("leaveData_"+a.crid,JSON.stringify({pages:c,crid:a.crid,viewId:a.viewId})),a.second++)}},1E3)},getCurrentPage:function(){for(var a,c=this.statData.pages,b=0;b<c.length;b++)c[b].id==this.currentPageId&&(a=c[b]);return a},entry:function(a){if(!this.isPreview&&
a)switch(a.type){case "loadTime":this.loadTime(a);break;case "updatePageTime":this.updatePageTime(a);break;case "interActions":this.interActions(a);break;case "playVideo":this.playVideo(a);break;case "stopVideo":this.stopVideo(a)}},loadTime:function(a){a=a.indexPageId;this.uploadData({crid:this.crid,viewId:this.viewId,loadTime:(new Date).valueOf()-performance.timing.connectStart,pages:[{id:a,stayTime:0}]});this.statData.pages.push({id:a,stayTime:0})},updatePageTime:function(a){var c=this.statData.pages;
if(c.length){for(var b=false,e=0;e<c.length;e++)c[e].id==a.toId&&(b=true);b||c.push({id:a.toId,stayTime:0})}else console.log("\u903b\u8f91\u9519\u8bef");b={crid:this.crid,viewId:this.viewId,pages:[],media:[]};for(e=0;e<c.length;e++)(c[e].id==a.fromId||c[e].id==a.toId)&&b.pages.push(c[e]);if(c=this.videoHash)for(var f in c)if(c[f].belong==a.fromId&&c[f].isUpdate)b.media.push({id:c[f].id,viewLength:c[f].viewLength}),c[f].isUpdate=false;this.currentPageId=a.toId;this.uploadData(b)},interActions:function(a){var c=
{crid:this.crid,viewId:this.viewId,pages:[],interactions:[],media:[]},b=this.getCurrentPage();b?(c.pages.push(b),c.interactions.push({id:a.id,action:a.action}),this.uploadData(c)):console.log("\u903b\u8f91\u9519\u8bef,\u6ca1\u6709\u62ff\u5230\u5f53\u524d\u9875\u6570\u636e.")},playVideo:function(a){var a=a.id,c=this.videoHash;c[a]?(c[a].startTime=(new Date).valueOf(),c[a].isUpdate=true):c[a]={id:a,viewLength:0,startTime:(new Date).valueOf(),belong:this.currentPageId,isUpdate:true}},stopVideo:function(a){var a=
a.id,c=this.videoHash;c[a]?(c[a].viewLength+=(new Date).valueOf()-c[a].startTime,c[a].startTime=(new Date).valueOf()):console.log("\u903b\u8f91\u9519\u8bef,\u6ca1\u6709\u627e\u5230\u89c6\u9891.")},getCookie:function(a){if(document.cookie.length>0&&(c_start=document.cookie.indexOf(a+"="),c_start!=-1)){c_start=c_start+a.length+1;c_end=document.cookie.indexOf(";",c_start);if(c_end==-1)c_end=document.cookie.length;return unescape(document.cookie.substring(c_start,c_end))}return""},setCookie:function(a,
c,b){var e=new Date,f=window.location.host.split("."),d=f.length,g="",g=d>=2?"."+f[d-2]+"."+f[d-1]:".mugeda.com";e.setDate(e.getDate()+b);document.cookie=a+"="+escape(c)+(b==null?"":";expires="+e.toGMTString())+"; domain="+g+"; path=/"},uploadData:function(a,c,b){var e=this;e.lockTime=true;a.media&&a.media.length===0&&delete a.media;a.msuid=e.msuid;var a=JSON.stringify(a),a=window.btoa(a),f=new Image;f.onload=function(){c&&
c();e.lockTime=false};f.onerror=function(){b&&b();e.lockTime=false};e.second=1}};
Mugeda.Analytics=function(a,c){var b=[],e=0;window._mrmcp=window._mrmcp||{};var f=_mrmcp.impression_pixel?_mrmcp.impression_pixel.indexOf("%TRACKURL%")>=0?"":_mrmcp.impression_pixel:"",a=a||f||"//cn-stat.mugeda.com/stats/c.gif",c=c||_mrmcp.eventUrl||a;this.setAccount=function(){};this.setCustomVar=function(a,c,d){a=a||0;b[a]&&delete b[a];b[a]={};b[a][c]=d||""};var d=function(a){if(document.cookie.length>0&&(c_start=document.cookie.indexOf(a+"="),c_start!=-1)){c_start=c_start+a.length+1;c_end=document.cookie.indexOf(";",
c_start);if(c_end==-1)c_end=document.cookie.length;return unescape(document.cookie.substring(c_start,c_end))}return""},g=function(){d("clientId");for(var a=[],c=0;c<b.length;c++)for(var e in b[c])a[c]=e+"="+encodeURIComponent(b[c][e]);return a.join("&")},k=function(){var a=location.pathname,b=/(?:\/animation\/edit)|(?:\/page\/edit)|(?:\/default\/preview\.html)|(?:\/client\/preview(?:_css3)?\.html)/;return!location.host||b.test(a)?false:true};this.trackPageview=function(b){if(k()){this.startTime=(new Date).getTime();
var c=a,f=new Image,r=c.indexOf("?")!=-1?"&":"?",j=_mrmcp.title||window._mrmma_title,m=+new Date,p=window.location.host,q=(_mrmcp.width||window._mrmma_width)+"x"+(_mrmcp.height||window._mrmma_height),l=window.location.href.slice(window.location.href.indexOf("/",8)),z=screen.width+"x"+screen.height,b=b||{};b.msv="0.1.0";b.msa="MU-A001";b.msh=p;b.mscs=q;b.msp=l;b.mssr=z;b.mssi=genSessionId(16);b.mscn=j;b.msct=m;b.crid=_mrmcp.creative_id||"";for(var y in b)b.hasOwnProperty(y)&&(this.setCustomVar(e,y,
b[y]),e++);b=d("msuid");if(!b)j=b=genSessionId(32),m=new Date,p=window.location.host.split("."),q=p.length,l="",l=q>=2?"."+p[q-2]+"."+p[q-1]:".mugeda.com",m.setDate(m.getDate()+3650),document.cookie="msuid="+escape(j)+(3650==null?"":";expires="+m.toGMTString())+"; domain="+l+"; path=/";this.setCustomVar(e++,"msuid",b);b=g();f.src=c+r+("mst=1&"+b)}};this.trackEvent=function(a){if(k()){var b=new Image,d=c,e=d.indexOf("?")!=-1?"&":"?",f=g(),a=a||{},m=(new Date).getTime(),p=m-this.startTime,q=encodeURIComponent(a.action||
"submit"),l=encodeURIComponent(a.categroy||"weika"),z=encodeURIComponent(a.label||""),a=parseInt(a.value)||0;b.src=d+e+f+"&mst=2&msts="+m+"&msetd="+p+"&msen="+q+"&msev="+a+"&msec="+l+"&msel="+z}}};try{window._mugeda_tracker=new Mugeda.Analytics,_mugeda_tracker.trackPageview()}catch(e$$27){}
function createFontFaceStyle(a,c,b,e,f,d,g){if(!c)return f&&f(a,null),a;var g=g||{},k="cloudfont-"+c;b&&(k+="-"+b);var h=document.getElementById(k),d=Object.prototype.toString.call(e)==="[object Array]"&&typeof f==="function",i=function(a){return(a=RegExp("[?&]"+a+"=([^&#]*)").exec(window.location.href))?a[1]:0};a.toLowerCase()=="simhei"?a='"Microsoft YaHei", "\u5fae\u8f6f\u96c5\u9ed1", SimHei, sans-serif':b&&(a+="-"+b);if(h)if(d&&g.useBlob&&h.data)return f(a,h.data),a;else if(!g.useBlob)return d&&
(c=h.textContent.match(/src:url\((.*?)\)/),f(a,c?c[1]:null)),a;for(var g=(g=i("fontApiType"))?g:3,h=e||["eot","eot","woff","ttf","svg"],t=c.indexOf("?")>-1?"&":"?",i=window.bd_version||i("v")||0,r=[],j=e&&e.length,m=e=0,p=function(a,c){var d=document.querySelector(".cloudfont_"+b);d&&document.head.removeChild(d);var e=document.createElement("style"),f,g=function(a){e.id=k;e.className="cloudfont_"+b;a=document.createTextNode(a);e.type="text/css";e.data=c;e.appendChild(a);document.head.appendChild(e)};
if(c&&c.type!="text/html"){var h,i=new window.FileReader;i.readAsDataURL(c);i.onloadend=function(){h=i.result;f="@font-face {font-family:'"+a+"';\nsrc:url("+h+");}";g(f)}}else a.indexOf("cloud-")!=0&&(f="@font-face {font-family:'"+a+"';}",g(f))},q=function(b){ajaxHelper({url:b,cache_ok:true,type:"data",success:function(b){++m===j&&typeof f==="function"&&(p(a,b),f(a,b))},error:function(a){a.status==414&&Mugeda.messageBox(Lang.M_TextTooLong);if(--j===0)throw f(false),"request font failed";}})},l=0,
z=h.length;l<z;l++){var y=c+t+"format="+h[l]+"&api_type="+g+"&v="+i,B="url("+y+")";if(l>0){var n=h[l];h[l]==="eot"?n="embedded-opentype":h[l]==="ttf"&&(n="truetype");B+=" format('"+n+"')"}r.push(B);d&&(e++,q(y))}if(d&&e===0)throw"request type invalid";return d?null:a}
Mugeda.messageBox=function(a,c,b,e){var e=e||{},f=document.createElement("div");f.id="message_holder_"+(new Date).getTime();f.style.display="block";f.style.position="absolute";f.style.left=0;f.style.top=0;f.style.width="100%";f.style.height="100%";f.style.zIndex=2E5;var d=document.createElement("div");d.className="messageMask";d.style.display="block";d.style.position="absolute";d.style.left=0;d.style.top=0;d.style.width="100%";d.style.height="100%";d.style.backgroundColor="rgba(0,0,0,0.5)";f.appendChild(d);
var c=c||"alert",g=document.createElement("div");g.className="messageInfo";g.style.display="block";g.style.position="absolute";g.innerHTML='<div class="messageBody">'+a+'</div><div align="center" class="messageConfirm '+c+'" onclick="onConfirmMessage();">'+(e.okText||"\u786e\u8ba4")+'</div><div align="center" class="messageCancel '+c+'" onclick="onCancelMessage();">'+(e.cancelText||"\u53d6\u6d88")+"</div>";f.appendChild(g);document.body.appendChild(f);f.querySelector(".messageConfirm").onclick=function(){document.body.removeChild(f);
b&&b(true)};f.querySelector(".messageCancel").onclick=function(){document.body.removeChild(f);b&&b(false)};f.querySelector(".messageMask").onclick=function(){g.className="messageInfo blinking";setTimeout(function(){g.className="messageInfo"},800)};a=document.getElementById("mugeda_message_styles");if(!a)a=document.createElement("style"),a.type="text/css",a.id="mugeda_message_styles",a.innerHTML=".messageBody { padding:32px; background-color: #fff; border-top-left-radius: 4px; border-top-right-radius: 4px; }.messageInfo { max-width: 512px; min-width: 256px; margin-left:50%; transform: translate(-50%, -50%); margin-top: 256px; font-size:14px; border: 4px solid rgba(0,0,0,0); border-radius:8px; line-height: 20px; }.messageConfirm, .messageCancel { width: 50%; display: inline-block; height: 48px; line-height: 48px; color: #fff; cursor: pointer; }.messageConfirm.alert { width: 100%; }.messageCancel.alert { display: none;}.messageCancel:active, .messageConfirm:active {-webkit-filter: brightness(115%);}.messageConfirm { background-color: #F36523; border-bottom-left-radius: 4px;}.messageInfo.blinking{ -webkit-animation: blinking 200ms infinite step-end; animation: blinking 200ms infinite step-end; }@-webkit-keyframes blinking {0% {border-color: rgba(255,0,0,0);} 50% {border-color: rgba(255,0,0,0.6);}}@keyframes blinking {0% { border-color: rgba(255,0,0,0);} 50% { border-color: rgba(255,0,0,0.6);}}.messageCancel { background-color: #999; border-bottom-right-radius: 4px;}",
document.body.appendChild(a)};
Mugeda.InstantMessage=function(){var a;return{show:function(c){var b=document.createElement("div"),e=b.appendChild(document.createElement("div")),f=e.appendChild(document.createElement("div")),d=e.appendChild(document.createElement("div"));b.style.cssText="position:fixed;left:0;right:0;top:0;bottom:0;text-align:center;line-height:"+(document.body.clientHeight||document.documentElement.clientHeight)+"px";e.style.cssText='padding-top:10px; line-height:30px;display:inline-block;padding:8px; min-width: 80px; background-color:rgba(0,0,0,0.6);border-radius:4px;"';e.align=
"center";f.style.cssText="width: 24px; height: 24px; display: block; border-radius: 50%; border-left: 2px solid #F36523; border-top: 2px solid #F36523; border-right: 2px solid white; border-bottom: 2px solid white; margin: 16px;";d.style.cssText='text-align:center;color:#fff;font:normal 12px "microsoft yahei";';d.innerHTML=c;a=document.body.appendChild(b);c=StyleSheetManager.insertKeyframes("from {"+Browser.prefix.css+"transform:rotate( 0deg ) }to {"+Browser.prefix.css+"transform:rotate( 360deg ) }");
f.style.cssText+=Browser.prefix.css+"animation:"+c+" 1200ms linear infinite;"},close:function(){a&&(a.parentNode.removeChild(a),a=null)}}}();